version: "3.9"
services:
  kerberos-agent1:
    image: "kerberos/agent:latest"
    ports:
      - "8081:80"
    environment:
      - AGENT_NAME=agent1
      # You can still override the configuration with environment variables, but might not makes sense if you are attaching a host config.
      # find full list of environment variables here: https://github.com/kerberos-io/agent#override-with-environment-variables
    volumes:
      - ./agent1:/home/agent/data/config
      - /mnt/c/unmanaged/agent1:/home/agent/data/recordings
