version: "3.9"
services:
  kerberos-agent1:
    image: "kerberos/agent:latest"
    ports:
      - "8081:80"
    environment:
      - AGENT_NAME=agent1
      - AGENT_USERNAME=abc
      - AGENT_PASSWORD=abc
      # You can still override the configuration with environment variables, but might not makes sense if you are attaching a host config.
      # find full list of environment variables here: https://github.com/kerberos-io/agent#override-with-environment-variables
    volumes:
      - ./agent1:/home/agent/data/config
      - /mnt/c/unmanaged/agent1:/home/agent/data/recordings
  kerberos-agent2:
    image: "kerberos/agent:latest"
    ports:
      - "8082:80"
    environment:
      - AGENT_NAME=agent2
      - AGENT_USERNAME=abc
      - AGENT_PASSWORD=abc
      # You can still override the configuration with environment variables, but might not makes sense if you are attaching a host config.
      # find full list of environment variables here: https://github.com/kerberos-io/agent#override-with-environment-variables
    volumes:
      - ./agent2:/home/agent/data/config
      - /mnt/c/unmanaged/agent2:/home/agent/data/recordings
  kerberos-agent3:
    image: "kerberos/agent:latest"
    ports:
      - "8083:80"
    environment:
      - AGENT_NAME=agent3
      - AGENT_USERNAME=abc
      - AGENT_PASSWORD=abc
      # You can still override the configuration with environment variables, but might not makes sense if you are attaching a host config.
      # find full list of environment variables here: https://github.com/kerberos-io/agent#override-with-environment-variables
    volumes:
      - ./agent3:/home/agent/data/config
      - /mnt/c/unmanaged/agent3:/home/agent/data/recordings
