version: "3.9"
services:
  kerberos-agent1:
    image: "kerberos/agent:latest"
    ports:
      - "8081:80"
    environment:
      - AGENT_NAME=${AGENT1_NAME}
      - AGENT_USERNAME=${AGENT1_USERNAME}
      - AGENT_PASSWORD=${AGENT1_PASSWORD}
      - AGENT_CAPTURE_IPCAMERA_RTSP=${AGENT1_CAPTURE_IPCAMERA_RTSP}
      - AGENT_CAPTURE_MAXLENGTH=${AGENT1_CAPTURE_MAXLENGTH}
      # You can still override the configuration with environment variables, but might not makes sense if you are attaching a host config.
      # find full list of environment variables here: https://github.com/kerberos-io/agent#override-with-environment-variables
    volumes:
      - ./agent1:/home/agent/data/config
      - /mnt/c/unmanaged/agent1:/home/agent/data/recordings
  kerberos-agent2:
    image: "kerberos/agent:latest"
    ports:
      - "8082:80"
    environment:
      - AGENT_NAME=${AGENT2_NAME}
      - AGENT_USERNAME=${AGENT2_USERNAME}
      - AGENT_PASSWORD=${AGENT2_PASSWORD}
      - AGENT_CAPTURE_IPCAMERA_RTSP=${AGENT2_CAPTURE_IPCAMERA_RTSP}
      - AGENT_CAPTURE_MAXLENGTH=${AGENT2_CAPTURE_MAXLENGTH}
      # You can still override the configuration with environment variables, but might not makes sense if you are attaching a host config.
      # find full list of environment variables here: https://github.com/kerberos-io/agent#override-with-environment-variables
    volumes:
      - ./agent2:/home/agent/data/config
      - /mnt/c/unmanaged/agent2:/home/agent/data/recordings
  kerberos-agent3:
    image: "kerberos/agent:latest"
    ports:
      - "8083:80"
    environment:
      - AGENT_NAME=${AGENT3_NAME}
      - AGENT_USERNAME=${AGENT3_USERNAME}
      - AGENT_PASSWORD=${AGENT3_PASSWORD}
      - AGENT_CAPTURE_IPCAMERA_RTSP=${AGENT3_CAPTURE_IPCAMERA_RTSP}
      - AGENT_CAPTURE_MAXLENGTH=${AGENT3_CAPTURE_MAXLENGTH}
      # You can still override the configuration with environment variables, but might not makes sense if you are attaching a host config.
      # find full list of environment variables here: https://github.com/kerberos-io/agent#override-with-environment-variables
    volumes:
      - ./agent3:/home/agent/data/config
      - /mnt/c/unmanaged/agent3:/home/agent/data/recordings
